Added new modules
stanriders/SkyBot pull request #1
Opened 2017-07-23 01:22 UTC by Binocl

Added Trigger as AI module
Added Boltun as AI module
Added Random as background service  module
Added YouTube as background service module
Added Organuser as tool module
Added Notepad as tool module

2017-07-23 01:26 UTC, stanriders commented
Во первых, не unsued, а unused. Во вторых, смысла в этой папке нет, особенно учитывая то, что в c# папки = неймспейсы

2017-07-23 16:05 UTC, stanriders requested changes

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
зачем public?

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        private string _dbFolderPath = "\\plugins\\MRandom.db";
Есть Configurable для такого

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
Ну и тоже Configurable мог бы сделать

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/AI/MTrigger.cs
> +    class TData
Каждый класс должен быть в своем файле

2017-07-23 16:05 UTC, stanriders commented on SkyBot/ReceivedMessage.cs
> +        public string Title;
Username звучит понятнее

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/AI/Unused/MBoltun.cs
> +                InformationCollector.Log("stage: 1\ninput: " + str + "\noutput: " + str_);
Все логи лучше вынести в `#if DEBUG`

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/Module_BasicCommands.cs
> +                StreamReader fs = new StreamReader(Directory.GetCurrentDirectory() + "\\changelog.txt", System.Text.Encoding.GetEncoding(1251));
File.ReadAllText()

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/Tools/MOrganiser.cs
> +    class TData
В отдельный файл

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/Tools/MOrganiser.cs
> +    class TData
И разве тут struct подойдет не лучше?

2017-07-23 16:05 UTC, stanriders commented on SkyBot/Modules/Tools/MOrganiser.cs
> +                        DateTime date = new DateTime(
DateTime.Parse?

2017-07-23 16:06 UTC, stanriders commented
Я не стал на каждый класс одни и те же претензии писать, например про Configurable, сам знаешь где ещё нужно так же сделать

2017-07-24 03:30 UTC, Binocl commented on SkyBot/ReceivedMessage.cs
> +        public string Title;
ChatID тоже лучше, чем Title. Взял по аналогии с VK API, как только будет реализовано для всех API корректное задание юзернейма, то можно будет переименовать.

2017-07-24 03:31 UTC, Binocl commented on SkyBot/Modules/AI/MTrigger.cs
> +    class TData
Это класс как шаблон данных, он нужен чисто для этого модуля и выносить его никуда не нужно. Это тебе не C++, здесь это добавит неудобства при редактировании (я периодически во время доработки менял набор тип переменных например)

2017-07-24 03:31 UTC, Binocl commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
Позже реализую, как хотел, пока не решил как

2017-07-24 03:33 UTC, Binocl commented on SkyBot/Modules/Module_BasicCommands.cs
> +                StreamReader fs = new StreamReader(Directory.GetCurrentDirectory() + "\\changelog.txt", System.Text.Encoding.GetEncoding(1251));
Это просто старый метод со старой версии еще, не помню, почему так было сделано. При доработке команд могу упростить

2017-07-24 03:34 UTC, Binocl commented on SkyBot/Modules/Tools/MOrganiser.cs
> +    class TData
Большого смысла в нем нет, не тот объем данных. Про файл написал выше

2017-07-24 03:37 UTC, Binocl commented on SkyBot/Modules/Tools/MOrganiser.cs
> +                        DateTime date = new DateTime(
Не хочется в который раз складывать строку, мне так нагляднее. Этот вопрос из разряда 
var + " text" или "{ var } text"

2017-07-24 04:58 UTC, stanriders commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
Ну если ты хочешь, чтобы настройки в интерфейсе работали, то придется юзать Configurable. Сам Configurable я потом скорее всего немного переделаю, но это уже после мерджа твои модулей

2017-07-24 05:01 UTC, stanriders commented on SkyBot/Modules/AI/MTrigger.cs
> +    class TData
Я в курсе, что это шаблон данных, но C# подразумевает каждый класс в отдельном файле, в отличии как раз таки от крестов. В целом не критично, мне самому привычнее подобные классы хранить в одном файле.

2017-07-24 05:02 UTC, stanriders commented on SkyBot/ReceivedMessage.cs
> +        public string Title;
ChatID это всё таки номер, а тут подразумевается имя отправителя

2017-07-24 05:12 UTC, stanriders commented
Ещё напоминаю, что проект всё ещё не компилится

2017-07-24 05:29 UTC, Binocl commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
Я думал в интерфейс добавить общий метод а-ля ProcessSettings или ProcessTrigger, куда будет слаться строка из BasicCommands, если там не найдено ничего по триггеру, а в модулях уже прогон свитчем и необходимые настройки над ним, как-то так.

2017-07-24 05:30 UTC, Binocl commented on SkyBot/ReceivedMessage.cs
> +        public string Title;
ChatID тоже лучше, чем Sender*, очепятка

2017-07-24 05:33 UTC, stanriders commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
Зачем, если каждый модуль прогоняет ProcessMessage, откуда уже можно настраивать нужный тебе Configurable?

2017-07-24 05:34 UTC, stanriders commented on SkyBot/ReceivedMessage.cs
> +        public string Title;
ChatID было бы не совсем верно, так как в разных апи отправитель называется по-разному

2017-07-24 05:37 UTC, Binocl commented on SkyBot/Modules/AI/Background/MRandom.cs
> +        public int _interval = 240;
Тоже верно. Тогда сделаю локально ProcessSettings там, где нужен, и все, со сменой настроек на приват.

2019-01-22 14:41 UTC, stanriders approved these changes

2019-01-22 14:56 UTC, merged

2019-01-22 14:57 UTC, stanriders commented
Че не ожидал да